### ISSUE TITLE
setting width of the SeasonSet to fit the window size

### ISSUE THREAD

**Issue by JacksiroKe** [MaterialDesignInXAML/F1InXAML#3]
Hi sir, am implenting your project in some project of mine and i cant find how to set width of the seasonset to fit the window size. I have checked everywhere but can't seem to figure out where

**Comment by JacksiroKe** [comment]
I found the answer to my issue by using HorizontalAlignment="Stretch"

**Comment by lucker2** [comment]
La lavadora es uno de los electrodomésticos más necesarios en cualquier hogar, más aún si hay niños que no dejan de ensuciar la ropa con comida, tierra, hierba, etc. La lavadora ocupa el cuarto puesto en consumo energético dentro del hogar y se usa una media de 200 veces al año, por lo que ya no basta con que las lavadoras sean eficientes, deben ser lavadoras ecoeficientes.

De ese modo, además de ayudarte a reducir el importe de tu factura energética mensual, también te ayudará a reducir el consumo de agua y de detergente, [reparación de secadoras madrid](http://madridindustriales.es/secadoras) lo cual suma un importante ahorro para tu economía familiar.

Las lavadoras TwinWash de LG cuentan con la última tecnología en el lavado de la ropa con la que se consigue optimizar el uso de los recursos para reducir el consumo energético y de agua en cada lavado necesarios para lograr una limpieza más eficiente y en el menor tiempo posible.

Las lavadoras con eficiencia energética A+++ son los modelos más eficientes del mercado. El consumo de una lavadora A+++ son capaces de lograr un consumo de hasta el 50 % menos en comparación con otros modelos con menor clasificación. No solo hay que optar por un modelo que cuente con al menos una clasificación energética [reparacion de secadoras madrid](http://www.madridsecadoras.com/916125277/reparacion-secadoras) A o superior, sino que es conveniente seguir consejos eficientes así como de ofrecer el buen mantenimiento de la lavadora.

Además, cabe señalar como cualquier lavadora bajo consumo de energía cuenta con las últimas innovaciones y tecnologías que ayudan a reducir el consumo mientras proporcionan un óptimo ciclo de lavado. También hay que tener en cuenta que las lavadoras de alta eficiencia energética suelen contar con una gran capacidad de carga [reparación de frigoríficos madrid](http://www.madridreparaciones.com/frigorificos) por lo que no solo se consigue un mayor ahorro sino que se puede introducir una gran cantidad de ropa sucia en el mismo ciclo de lavado.
